###Experiment No - 11
##Categorical Data Analysis using Python
##Jai Pratap
##PRN - 25070123056
##Branch - ENTC A3

In [ ]:
import pandas as pd
data = {
    'Order_ID':['01','02','03','04','05','06','07','08','09','10'],

    'Category':['Electronics','Clothing','Electronics','Grocery','Clothing',
                'Electronics','Grocery','Clothing','Electronics','Grocery'],

    'Payment_Method':['UPI','Card','UPI','Cash','Card',
                       'UPI','Cash','Card','UPI','Cash'],

    'Delivery_Type':['Express','Standard','Express','Standard','Express',
                      'Standard','Express','Standard','Express','Standard'],

    'Customer_Type':['New',"Returning","Returning","New","Returning",
                      'New','Returning','New','Returning','New']
}

df = pd.DataFrame(data)
df

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       01  Electronics            UPI       Express           New
1       02     Clothing           Card      Standard     Returning
2       03  Electronics            UPI       Express     Returning
3       04      Grocery           Cash      Standard           New
4       05     Clothing           Card       Express     Returning
5       06  Electronics            UPI      Standard           New
6       07      Grocery           Cash       Express     Returning
7       08     Clothing           Card      Standard           New
8       09  Electronics            UPI       Express     Returning
9       10      Grocery           Cash      Standard           New

In [ ]:
#1 Frequency Count
#Count how many orders in each category
print(df['Category'].value_counts())
print()
print(df['Payment_Method'].value_counts())
print()
print(df['Customer_Type'].value_counts())
print()
print(df['Delivery_Type'].value_counts())

Category
Electronics    4
Clothing       3
Grocery        3
Name: count, dtype: int64

Payment_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

Customer_Type
New          5
Returning    5
Name: count, dtype: int64

Delivery_Type
Express     5
Standard    5
Name: count, dtype: int64

In [ ]:
#2 Unique Values
#Display all unique categories
print(df['Category'].unique())
print()
print(df['Payment_Method'].unique())
print()
print(df['Customer_Type'].unique())
print()
print(df['Delivery_Type'].unique())

['Electronics' 'Clothing' 'Grocery']

['UPI' 'Card' 'Cash']

['New' 'Returning']

['Express' 'Standard']

In [ ]:
#3 Number of unique values
print("Category :",df['Category'].nunique())
print()
print("Payment Method ;",df['Payment_Method'].nunique())
print()
print("Customer Type :",df['Customer_Type'].nunique())
print()
print("Delivery Type:",df['Delivery_Type'].nunique())

Category : 3

Payment Method ; 3

Customer Type : 2

Delivery Type: 2

In [ ]:
#4 Cross Tabulation
# Category VS Payment Method
print(pd.crosstab(df['Category'],df['Payment_Method']))

Payment_Method  Card  Cash  UPI
Category
Clothing           3     0    0
Electronics        0     0    4
Grocery            0     3    0

In [ ]:
#5 Cross Tabulation
# Customer Type VS Delivery Method
print(pd.crosstab(df['Delivery_Type'],df['Customer_Type']))

Customer_Type  New  Returning
Delivery_Type
Express          1          4
Standard         4          1

In [ ]:
#6 Percentage Distribution
print(df['Category'].value_counts(normalize=True)*100)

Category
Electronics    40.0
Clothing       30.0
Grocery        30.0
Name: proportion, dtype: float64

In [ ]:
#7 Filtering Data
print(df[df['Category']=='Electronics'])

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       01  Electronics            UPI       Express           New
2       03  Electronics            UPI       Express     Returning
5       06  Electronics            UPI      Standard           New
8       09  Electronics            UPI       Express     Returning

In [ ]:

#8 Grouping
#Order by category and payment method
print(df.groupby('Category')['Payment_Method'].value_counts())

Category     Payment_Method
Clothing     Card              3
Electronics  UPI               4
Grocery      Cash              3
Name: count, dtype: int64

In [ ]:

#for me
# grouping
#order by category and payment method
print(df.groupby(['Category','Payment_Method']).value_counts())

Category     Payment_Method  Order_ID  Delivery_Type  Customer_Type
Clothing     Card            02        Standard       Returning        1
                             05        Express        Returning        1
                             08        Standard       New              1
Electronics  UPI             01        Express        New              1
                             03        Express        Returning        1
                             06        Standard       New              1
                             09        Express        Returning        1
Grocery      Cash            04        Standard       New              1
                             07        Express        Returning        1
                             10        Standard       New              1
Name: count, dtype: int64

In [ ]:
#9 Sorting Data
sorted_df = df.sort_values(by='Order_ID')
sorted_df

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       01  Electronics            UPI       Express           New
1       02     Clothing           Card      Standard     Returning
2       03  Electronics            UPI       Express     Returning
3       04      Grocery           Cash      Standard           New
4       05     Clothing           Card       Express     Returning
5       06  Electronics            UPI      Standard           New
6       07      Grocery           Cash       Express     Returning
7       08     Clothing           Card      Standard           New
8       09  Electronics            UPI       Express     Returning
9       10      Grocery           Cash      Standard           New

In [ ]:
import pandas as pd

df = pd.read_csv("/content/data.csv")
print(df.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
print(df.columns)

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
#1 Count students in Each Grade
# Find how many students obtained each grade
print("Each Grade :",df['Duration'].value_counts())

Each Grade : Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
75      2
160     2
210     2
15      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [ ]:
#2 Percentage Distribution of Grades
print(df['Duration'].value_counts(normalize=True)*100)

Duration
60     46.745562
45     20.710059
30      9.467456
20      5.325444
90      4.733728
150     2.366864
180     1.775148
120     1.775148
75      1.183432
160     1.183432
210     1.183432
15      1.183432
80      0.591716
300     0.591716
270     0.591716
25      0.591716
Name: proportion, dtype: float64

In [ ]:
#3 Number of students in Each department
print(df['Pulse'].value_counts())

Pulse
100    19
90     12
103     9
109     9
107     8
108     7
97      7
110     7
106     6
102     6
105     6
111     6
98      6
104     4
114     4
118     3
92      3
117     3
93      3
115     3
136     3
95      3
123     2
112     2
99      2
151     2
101     2
80      2
150     2
130     1
121     1
129     1
149     1
159     1
153     1
152     1
137     1
124     1
83      1
116     1
119     1
113     1
141     1
122     1
85      1
120     1
125     1
Name: count, dtype: int64

In [ ]:
#4 Pulse Distribution
print(df['Pulse'].value_counts())

Pulse
100    19
90     12
103     9
109     9
107     8
108     7
97      7
110     7
106     6
102     6
105     6
111     6
98      6
104     4
114     4
118     3
92      3
117     3
93      3
115     3
136     3
95      3
123     2
112     2
99      2
151     2
101     2
80      2
150     2
130     1
121     1
129     1
149     1
159     1
153     1
152     1
137     1
124     1
83      1
116     1
119     1
113     1
141     1
122     1
85      1
120     1
125     1
Name: count, dtype: int64

In [ ]:
#5 Duration vs Pulse
print(pd.crosstab(df['Duration'],df['Pulse']))

Pulse     80   83   85   90   92   93   95   97   98   99   ...  130  136  \
Duration                                                    ...
15          1    0    0    0    0    0    0    0    0    0  ...    0    0
20          0    1    0    0    0    0    1    0    0    0  ...    0    1
25          0    0    0    0    0    0    0    0    0    0  ...    0    0
30          1    0    1    2    1    1    1    0    0    0  ...    0    1
45          0    0    0    4    0    0    1    1    0    0  ...    0    0
60          0    0    0    0    2    1    0    4    5    1  ...    1    1
75          0    0    0    0    0    0    0    0    0    0  ...    0    0
80          0    0    0    0    0    0    0    0    0    0  ...    0    0
90          0    0    0    4    0    1    0    0    1    1  ...    0    0
120         0    0    0    0    0    0    0    0    0    0  ...    0    0
150         0    0    0    0    0    0    0    2    0    0  ...    0    0
160         0    0    0    0    0    0    0    0    0    0  ...    0    0
180         0    0    0    2    0    0    0    0    0    0  ...    0    0
210         0    0    0    0    0    0    0    0    0    0  ...    0    0
270         0    0    0    0    0    0    0    0    0    0  ...    0    0
300         0    0    0    0    0    0    0    0    0    0  ...    0    0

Pulse     137  141  149  150  151  152  153  159
Duration
15          0    0    0    0    0    0    0    0
20          0    1    0    1    1    0    1    0
25          0    0    0    0    0    1    0    0
30          0    0    0    1    1    0    0    1
45          0    0    1    0    0    0    0    0
60          0    0    0    0    0    0    0    0
75          0    0    0    0    0    0    0    0
80          0    0    0    0    0    0    0    0
90          0    0    0    0    0    0    0    0
120         0    0    0    0    0    0    0    0
150         0    0    0    0    0    0    0    0
160         0    0    0    0    0    0    0    0
180         0    0    0    0    0    0    0    0
210         1    0    0    0    0    0    0    0
270         0    0    0    0    0    0    0    0
300         0    0    0    0    0    0    0    0

[16 rows x 47 columns]

In [ ]:
#6 Pulse vs Calories
print(pd.crosstab(df['Pulse'],df['Calories']))

Calories  50.3    50.5    77.7    86.2    92.7    100.7   105.3   110.4   \
Pulse
80             0       1       0       0       0       0       0       0
83             1       0       0       0       0       0       0       0
85             0       0       0       0       0       0       0       0
90             0       0       0       1       0       0       1       0
92             0       0       0       0       1       0       0       0
93             0       0       0       0       0       0       0       0
95             0       0       1       0       0       0       0       0
97             0       0       0       0       0       0       0       0
98             0       0       0       0       0       0       0       0
99             0       0       0       0       0       0       0       0
100            0       0       0       0       0       1       0       0
101            0       0       0       0       0       0       0       0
102            0       0       0       0       0       0       0       0
103            0       0       0       0       0       0       0       0
104            0       0       0       0       0       0       0       0
105            0       0       0       0       0       0       0       0
106            0       0       0       0       0       0       0       1
107            0       0       0       0       0       0       0       0
108            0       0       0       0       0       0       0       0
109            0       0       0       0       0       0       0       0
110            0       0       0       0       0       0       0       0
111            0       0       0       0       0       0       0       0
112            0       0       0       0       0       0       0       0
113            0       0       0       0       0       0       0       0
114            0       0       0       0       0       0       0       0
115            0       0       0       0       0       0       0       0
116            0       0       0       0       0       0       0       0
117            0       0       0       0       0       0       0       0
118            0       0       0       0       0       0       0       0
119            0       0       0       0       0       0       0       0
120            0       0       0       0       0       0       0       0
121            0       0       0       0       0       0       0       0
122            0       0       0       0       0       0       0       0
123            0       0       0       0       0       0       0       0
124            0       0       0       0       0       0       0       0
125            0       0       0       0       0       0       0       0
129            0       0       0       0       0       0       0       0
130            0       0       0       0       0       0       0       0
136            0       0       0       0       0       0       0       0
137            0       0       0       0       0       0       0       0
141            0       0       0       0       0       0       0       0
149            0       0       0       0       0       0       0       0
150            0       0       0       0       0       0       0       0
151            0       0       0       0       0       0       0       0
152            0       0       0       0       0       0       0       0
153            0       0       0       0       0       0       0       0
159            0       0       0       0       0       0       0       0

Calories  124.0   124.2   ...  853.0   873.4   953.2   1000.1  1034.4  1115.0  \
Pulse                     ...
80             0       0  ...       0       0       0       0       0       0
83             0       0  ...       0       0       0       0       0       0
85             0       0  ...       0       0       0       0       0       0
90             0       0  ...       0       0       0       0       0       0
92             0       0  ...       0       0       0       0       0       0
93             1       0  ...       0       0       0       0       0       0
95             0       0  ...       0       0       0       0       0       0
97             0       0  ...       0       0       1       0       0       1
98             0       0  ...       0       0       0       0       0       0
99             0       0  ...       0       0       0       0       0       0
100            0       0  ...       0       0       0       1       0       0
101            0       0  ...       0       0       0       0       0       0
102            0       0  ...       0       0       0       0       0       0
103            0       0  ...       0       0       0       0       0       0
104            0       0  ...       0       0       0       0       0       0
105            0       0  ...       0       1       0       0       0       0
106            0       0  ...       0       0       0       0       0       0
107            0       0  ...       0       0       0       0       0       0
108            0       0  ...       0       0       0       0       0       0
109            0       0  ...       1       0       0       0       0       0
110            0       0  ...       0       0       0       0       1       0
111            0       0  ...       0       0       0       0       0       0
112            0       0  ...       0       0       0       0       0       0
113            0       0  ...       0       0       0       0       0       0
114            0       0  ...       0       0       0       0       0       0
115            0       0  ...       0       0       0       0       0       0
116            0       0  ...       0       0       0       0       0       0
117            0       0  ...       0       0       0       0       0       0
118            0       0  ...       0       0       0       0       0       0
119            0       0  ...       0       0       0       0       0       0
120            0       0  ...       0       0       0       0       0       0
121            0       0  ...       0       0       0       0       0       0
122            0       0  ...       0       0       0       0       0       0
123            0       0  ...       0       0       0       0       0       0
124            0       1  ...       0       0       0       0       0       0
125            0       0  ...       0       0       0       0       0       0
129            0       0  ...       0       0       0       0       0       0
130            0       0  ...       0       0       0       0       0       0
136            0       0  ...       0       0       0       0       0       0
137            0       0  ...       0       0       0       0       0       0
141            0       0  ...       0       0       0       0       0       0
149            0       0  ...       0       0       0       0       0       0
150            0       0  ...       0       0       0       0       0       0
151            0       0  ...       0       0       0       0       0       0
152            0       0  ...       0       0       0       0       0       0
153            0       0  ...       0       0       0       0       0       0
159            0       0  ...       0       0       0       0       0       0

Calories  1376.0  1500.2  1729.0  1860.4
Pulse
80             0       0       0       0
83             0       0       0       0
85             0       0       0       0
90             0       0       0       0
92             0       0       0       0
93             0       0       0       0
95             0       0       0       0
97             0       0       0       0
98             0       0       0       0
99             0       0       0       0
100            0       0       1       0
101            0       0       0       0
102            0       0       0       0
103            0       0       0       0
104            0       0       0       0
105            0       0       0       0
106            0       0       0       0
107            0       0       0       0
108            1       1       0       0
109            0       0       0       0
110            0       0       0       0
111            0       0       0       0
112            0       0       0       0
113            0       0       0       0
114            0       0       0       0
115            0       0       0       0
116            0       0       0       0
117            0       0       0       0
118            0       0       0       0
119            0       0       0       0
120            0       0       0       0
121            0       0       0       0
122            0       0       0       0
123            0       0       0       0
124            0       0       0       0
125            0       0       0       0
129            0       0       0       0
130            0       0       0       0
136            0       0       0       0
137            0       0       0       1
141            0       0       0       0
149            0       0       0       0
150            0       0       0       0
151            0       0       0       0
152            0       0       0       0
153            0       0       0       0
159            0       0       0       0

[47 rows x 142 columns]

In [ ]:
#7 Duration vs Pulse Percentage
print(pd.crosstab(df['Duration'],df['Pulse'].value_counts(normalize=True)*100))

proportion  0.591716   1.183432   1.775148   2.366864   3.550296   4.142012   \
Duration
15                  0          1          1          0          0          0
20                  0          0          1          0          0          0
25                  0          0          0          0          0          1
30                  4          1          1          1          2          0
45                  3          0          1          0          1          0
60                 10          3          3          1          0          1
90                  0          2          0          0          1          1
120                 1          0          0          0          0          0
180                 0          0          0          0          1          0
210                 0          0          0          0          0          0

proportion  4.733728   5.325444   7.100592   11.242604
Duration
15                  0          0          0          0
20                  0          0          0          1
25                  0          0          0          0
30                  1          0          0          0
45                  0          0          0          0
60                  0          0          0          0
90                  0          1          0          0
120                 0          0          0          0
180                 0          0          1          0
210                 0          1          0          0

In [ ]:
# Grouping Data (Duration-wise)
print(df.groupby('Duration').value_counts())

Duration  Pulse  Maxpulse  Calories
15        80     100       50.5        1
          124    139       124.2       1
20        83     107       50.3        1
          95     112       77.7        1
          106    136       110.4       1
                                      ..
180       101    127       600.1       1
210       108    160       1376.0      1
          137    184       1860.4      1
270       100    131       1729.0      1
300       108    143       1500.2      1
Name: count, Length: 157, dtype: int64