###Experiment - 9
##Study of Pandas
##Jai Pratap
##ENTC A3
##PRN - 25070123056

In [ ]:
# Initialisation of Pandas

import pandas as pd

s = pd.Series([1, 3, 5, 6, 8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [ ]:
# Create a Dataframe

data = {
    "Name" : ["Parth", "Anik", "Jai", "Krish", "Kshitij"],
    "Marks" : [95, 100, 93, 85, 89]
}
df = pd.DataFrame(data)
df

      Name  Marks
0    Parth     95
1     Anik    100
2      Jai     93
3    Krish     85
4  Kshitij     89

In [ ]:
df.head

<bound method NDFrame.head of       Name  Marks
0    Parth     95
1     Anik    100
2      Jai     93
3    Krish     85
4  Kshitij     89>

In [ ]:
df.tail

<bound method NDFrame.tail of       Name  Marks
0    Parth     95
1     Anik    100
2      Jai     93
3    Krish     85
4  Kshitij     89>

In [ ]:
''' if nothing is mentioned in the bracet then first and last five is printed
for head and tail function. Nut, the number of rows to be printed can be changed'''

df.head(2)

    Name  Marks
0  Parth     95
1   Anik    100

In [ ]:
df.tail(3)

      Name  Marks
2      Jai     93
3    Krish     85
4  Kshitij     89

In [ ]:

# Find the structure of the dataframe

df.shape

(5, 2)

In [ ]:
# To check the number of columns

df.ndim

2

In [ ]:
# To check the number of columns

df.ndim

2

In [ ]:
# Total number of elements = no of columns x no of rows

df.size

10

In [ ]:
# Display column Names

df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:

# Check Data Types of each Column
# object   -   Categorical data
# int64    -   Numerical Data

df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
# Access Individual Column

df["Name"]

0      Parth
1       Anik
2        Jai
3      Krish
4    Kshitij
Name: Name, dtype: object

In [ ]:
# Access Individual Column

df["Name"]

0      Parth
1       Anik
2        Jai
3      Krish
4    Kshitij
Name: Name, dtype: object

In [ ]:
# Access Specific Row

df.loc[3]

Name     Krish
Marks       85
Name: 3, dtype: object

In [ ]:
# Add a New Column

df["Grade"] = ["First Class", "Distinction", "First Class", "Second Class", "Second Class"]

df

      Name  Marks         Grade
0    Parth     95   First Class
1     Anik    100   Distinction
2      Jai     93   First Class
3    Krish     85  Second Class
4  Kshitij     89  Second Class

In [ ]:
# Update Data in DataFrame
# Change marks of third student to 97

df.loc[2, "Marks"] = 100
df.loc[2, "Grade"] = "Distinction"
df

      Name  Marks         Grade
0    Parth     95   First Class
1     Anik    100   Distinction
2      Jai    100   Distinction
3    Krish     85  Second Class
4  Kshitij     89  Second Class

In [ ]:

# Delete a Column

df.drop("Grade", axis=1, inplace = True)
''' axis = 1 --> column, axis = 0 --> row '''
''' inplace is used to make the changes permanently to the dataframe'''
df

      Name  Marks
0    Parth     95
1     Anik    100
2      Jai    100
3    Krish     85
4  Kshitij     89

In [ ]:
# Perform Basic Statistical Analysis

meandf = df["Marks"].mean()
print("Mean: ", meandf)

Mean:  93.8

In [ ]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Kahaan", "Krishif", "Parth"],
    "Marks": [85, 91, 77]
}

df = pd.DataFrame(data)

# Calculate mode
modedf = df["Marks"].mode()

print("Mode:", modedf)

Mode: 0    77
1    85
2    91
Name: Marks, dtype: int64

In [ ]:

# Aggregate Functions in Data Frames

min_value = df["Marks"].min()
max_value = df["Marks"].max()
sum_value = df["Marks"].sum()

print("Maximum of Marks: ", max_value)
print("Minimum Value of Marks: ", min_value)
print("Sum of Marks: ", sum_value)

Maximum of Marks:  91
Minimum Value of Marks:  77
Sum of Marks:  253

In [ ]:
# Apply conditions (Filtering)
# Display Students who scored more than 90

df[df["Marks"] > 90]

      Name  Marks
1  Krishif     91

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1': [11,21, np.nan], 'C2': [15, np.nan, np.nan], 'C3': [10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna() #Boolean Function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.notna() # Boolean function indicating non-missing values

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
df1.isna().sum() #Column-wise NaN values

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna() #NaN Rows are dropped

     C1    C2  C3
0  11.0  15.0  10